name: fetch-arcticdem
channels:
  - conda-forge
dependencies:
  - python=3.11.12
  - numpy=2.3.3
  - pandas=2.2.3
  - xarray=2025.4.0
  - rioxarray=0.19.0
  - geopandas=1.0.1
  - shapely=2.1.0
  - rasterio=1.4.3
  - gdal=3.10.3
  - pystac=1.13.0
  - pystac-client=0.9.0
  - stac-geoparquet=0.6.0
  - odc-stac
  - xdem=0.1.6
  - geoutils=0.1.17
  - dask=2024.12.1
  - pytransform3d=3.14.3
  - ruff
  - pytest